# Generated by Django 5.2.17 on 2026-09-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(max_length=100)),
                ('short_description', models.TextField(max_length=500)),
                ('full_description', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True, help_text='Project overview summary')),
                ('problem', models.TextField(blank=True, help_text='What problem does this project solve?')),
                ('approach', models.TextField(blank=True, help_text='How was this project built?')),
                ('solution', models.TextField(blank=True, help_text='What is the solution developed?')),
                ('engineering', models.TextField(blank=True, help_text='Engineering and architecture details')),
                ('features', models.JSONField(blank=True, default=list, help_text='List of key features (JSON array of strings)')),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technology names (JSON array of strings)')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False, help_text='Show in featured projects section')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('languages', 'Languages'), ('ml_data', 'Machine Learning & Data'), ('tools', 'Tools'), ('database', 'Database'), ('backend', 'Backend'), ('web_dev', 'Web Development')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier or emoji', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
